### ISSUE TITLE
add dates argument to EstimateR and WT

### ISSUE THREAD

**Issue by annecori** [annecori/EpiEstim#12]
could be used for plotting as the x axis

**Comment by jstockwin** [comment]
@annecori Rather than a new argument, would it be better to just allow a "dates" column in the incidence data, `I`?

**Comment by annecori** [comment]
this should be sorted in the new version in the dates branch; @jstockwin could you please have a look and let me know if you're happy with the way I've felt with this? thanks.

**Comment by annecori** [comment]
in short, I can now have a column containing dates, and there is a date_col argument to indicate which column that is - I am actually thinking this could be simplified so there is no date_col argument but this is automatically detected using the name of the column in I...

**Comment by jstockwin** [comment]
@annecori I'll have a look a bit later. Can you open it as a PR into the hackout branch so I can easily see the doff, please?

**Comment by annecori** [comment]
will do once I've simplified things the way I was explaining above!

**Comment by annecori** [comment]
one thing left to do here is maybe allow T.Start and T.End to be dates rather than integers when I does have a dates column...

**Comment by jstockwin** [comment]
Closed by #20
