### ISSUE TITLE
Incorrect error thrown

### ISSUE THREAD

**Issue by jstockwin** [annecori/EpiEstim#17]
```
> I <- data.frame(c(0,0,2,2,3,3), c(1,0,0,0,0,0))
> colnames(I) <- c("local", "imported")
> 
> EstimateR(I, T.Start=1:5, T.End=2:6, method="ParametricSI")
Error in EstimateR_func(I = I, T.Start = T.Start, T.End = T.End, method = method,  : 
  method NonParametricSI requires to specify the Mean.SI argument.
```
The above code gives the above error, as shown. However, the text in the error says `method NonParametricSI` when in fact the method I am trying to use is `ParametricSI`. It's probably just the wording that needs updating.

**Comment by annecori** [comment]
well spotted thanks - just fixed.
