### ISSUE TITLE
Incidence data output with imported cases

### ISSUE THREAD

**Issue by jstockwin** [annecori/EpiEstim#18]
Currently, the output of EpiEstim relating to the incidence data is as follows:
```
$I
 [1] 1 0 2 2 3 3 2 3 3 2

$I_local
 [1] 0 0 2 2 3 3 2 2 3 2

$I_imported
 [1] 1 0 0 0 0 0 0 1 0 0
```

This seems strange. In particular, `I` does not look as it did when I gave it to EpiEstim (before, I have a data frame with `local` and `imported` columns). 

This results in the (in progress) EpiEstimApp not displaying the incidence data table correctly (as we're just showing a table of `I`. Obviously, I can change how I handle the output, but it seems to be that the output `I` here should be exactly the (processed) version of what was passed in in the first place (i.e. a data frame with two variables, `local` and `imported`). What do you think, @annecori?

**Comment by annecori** [comment]
The reason I did this is to remain consistent with the previous version of the package, where I, the input of EpiEstim, was always a vector, and $I was a vector as well as a result. Therefore I would rather keep the output as is and the issue be felt with by the user (or in the app if that's for the app). This should be quite straightforward to reconstruct from the $I_local and $I_imported outputs.

**Comment by jstockwin** [comment]
Fair enough. I agree it's no problem to reconstruct.
