### ISSUE TITLE
R session aborted when using the Wallinga and Teunis method to estimate case reproduction number

### ISSUE THREAD

**Issue by caijun** [annecori/EpiEstim#2]
Hi Anne Cori,

I am using EpiEstim to estimate the instantaneous (case) reproduction number for 2009 pandemic influenza A (H1N1) in mainland China. The following are my code:

```
rm(list = ls())

load(url("http://tonytsai.name/confirmed_pdm_dec.rda"))

# instantaneous reproduction number estimation for pandemic --------------------
# using ParametricSI method
# the instantaneous reproduction number can be estimated after May 22nd, 2009
EstimateR(dec$cases, T.Start = 22:359, T.End = 28:365, method = "ParametricSI", 
          Mean.SI = 2.6, Std.SI = 1.3, plot = TRUE, leg.pos = xy.coords(1, 3))
# case reproduction number estimaion for pandemic ------------------------------
# using the Wallinga and Teunis method
WT(dec$cases, T.Start = 20:100, T.End = 26:106, method = "ParametricSI", Mean.SI = 2.6, 
   Std.SI = 1.3, plot = TRUE, nSim = 100)
```

The instantaneous reproduction number can be successfully estimated, but the `WT` function failed and the R session aborted. 

![image](https://cloud.githubusercontent.com/assets/2522593/19909489/60b823c8-a05e-11e6-853c-48c9b1852ae6.png)

Could you help me to fix the problem with `WT` function? Thank you very much.

**Comment by annecori** [comment]
Hi there, 
I had a look and this was an issue with memory size - because your dataset has a large number of cases, and because of the way I had coded the function WT this was creating issues. I have changed the code so the version now on github should work - please can you try and let me know? 
Many thanks

**Comment by caijun** [comment]
I tried to install the version on github, but encountered following error

```
cannot open file 'Z:/Hackout3/EpiEstim/R/EstimationR.R': No such file or directory
```

I think the `runWholeThing.R` and `stochasticSEIRModel3.R` are not necessary files to install EpiEstim package. Here is my suggestion: on the master branch you'd better store the ready installation version. And on other branches, you can develop new features for the package. After the development is finished and cleaning the code, you can merged the developing branch into master branch.

Perhaps I can fork EpiEstim repository and do the code-cleaning. After I have done the task, I can pull a request.

**Comment by annecori** [comment]
Hi Tony, 
sorry about that - the version here is indeed a development version... 
Can you maybe download the files and copy the code of the function WT into your own script to overwrite that from EpiEstim from CRAN? Then see if that works? 
I will try and spend some time tidying up all this next week
Thanks

**Comment by caijun** [comment]
Hi Anne, 

The new `WT` function works and the following is the result for my example.

![image](https://cloud.githubusercontent.com/assets/2522593/19970250/d0d6ef32-a1b1-11e6-8f35-6312444cbe3f.png)

I am looking forward to your new, tidy version of EpiEstim package on CRAN. Thank you very much.

**Comment by annecori** [comment]
no problem thank you for your patience and for using EpiEstim!

**Comment by caijun** [comment]
One more question on the plot: my estimations of reproduction number  are up to the 365th day, but the range of x-axis of epidemic curve and reproduction number estimation plots is only up to 300? Is it possible for me to customize the plot range in the `EstimateR` function? Or after I get the returning results from `EstimateR` function, I plot those figures by myself?

**Comment by annecori** [comment]
There is no automatic way of doing this at the moment - but we are working on improving the plots altogether - so I suggest for now you tweak the code yourself to do that - or plot from the output - and hopefully in the next few weeks/months there will be a new version with better and more flexible plots!

**Comment by caijun** [comment]
OK, I see. Thank you very much.
