### ISSUE TITLE
[SIFromSample] Choosing `n2=1` gives an unexpected error

### ISSUE THREAD

**Issue by jstockwin** [annecori/EpiEstim#23]
```
> epiEstimOut <- EstimateR(I, T.Start=2:26, T.End=8:32, SI.Sample=sample, method="SIFromSample", n2=1, seed=1)
Error in (temp[[k]])[[1]][, which(T.End > Mean.SI.sample[k])] : 
  incorrect number of dimensions
```
An example of the `I` and `sample` I used is [this csv](https://github.com/jstockwin/EpiEstimApp/blob/master/inst/app/datasets/IncidenceData/FluPennsylvania2009.csv) and [this csv](https://github.com/jstockwin/EpiEstimApp/blob/master/inst/app/datasets/SIPosteriorSamples/RotavirusEcuador2011_SISamples_G.csv) respectively, but this doesn't seem to matter.

**Comment by annecori** [comment]
fixed in #41
