### ISSUE TITLE
Externalise config

### ISSUE THREAD

**Issue by thibautjombart** [annecori/EpiEstim#54]
The config argument in `estimate_R` should be externalised, i.e. moved outside the function and treated separately, so that we'd use something like:
```
config <- make_config(...)
res <- estimate_R(x, config = config)
```
This has the following advantages:

- easier to test that config is valid
- seamless defaults
- `estimate_R` easier to use once config is defined
- document config separately 

An example of this can be found in *outbreaker2*:
http://www.repidemicsconsortium.org/outbreaker2/reference/create_config.html

coded there:
https://github.com/reconhub/outbreaker2/blob/master/R/create_config.R

**Comment by annecori** [comment]
branch config created to do this. Seems to work but could edit examples everywhere to use this new formulation
