### ISSUE TITLE
plot several R at a time

### ISSUE THREAD

**Issue by annecori** [annecori/EpiEstim#62]
this doesn't seem to work anymore (used to work with `plots` function

**Comment by annecori** [comment]
@zkamvar can you please help with this? this is the issue: I'm trying to allow plotting several `estimate_R` objects at a time. this will work if I specifically use `plot.estimate_R` but not if I use `plot` because the list I naively generate is not an object of class `estimate_R`. Any way we can get a list which inherits the class of each of its elements? 
So in the following, the first `plot` call doesn't work while the second one does; if possible I would like the first call to `plot` to do the same as the second...
any help appreciated!
```data(Flu2009)

R_i <- estimate_R(Flu2009$incidence,
                                     method = "non_parametric_si",
                                     config = list(t_start = seq(2, 26), 
                                                   t_end = seq(8, 32), 
                                                   si_distr = Flu2009$si_distr
                                                  )
                                    )
                  
R_i_2 <- estimate_R(Flu2009$incidence + 6,
                  method = "non_parametric_si",
                  config = list(t_start = seq(2, 26), 
                                t_end = seq(8, 32), 
                                si_distr = Flu2009$si_distr
                  )
)

plot(list(R_i, R_i_2), legend = FALSE)
plot.estimate_R(list(R_i, R_i_2), legend = FALSE)
```

**Comment by zkamvar** [comment]
I.... was unaware it could do that!

**Comment by zkamvar** [comment]
Hi Anne,

I think the best way to do this would be to add a function called  `estim_plots()` that will just pass the list of objects to `plot.estimate_R()`:

```r
estim_plots <- function(..., legend = FALSE) {
   plot.estimate_R(..., legend = legend)
}
```
