### ISSUE TITLE
Consolidate `new-version` branch with `release`

### ISSUE THREAD

**Issue by zkamvar** [annecori/EpiEstim#63]
There are two branches that are ahead of master, `new-version` and `release`. It is confusing why both of these should be ahead of master. When comparing these, it appears that `release` may be slightly ahead of `new-version` and should be favored: https://github.com/annecori/EpiEstim/compare/new-version..release

**Comment by zkamvar** [comment]
Scratch that, and reverse it. New version appears to have one more feature from 7680cea

**Comment by jstockwin** [comment]
Hey @zkamvar, apologies for the confusion. We're aware of this and will try to get around to resolving it as soon as possible!

The plan is to get both branches merged in to master!

**Comment by annecori** [comment]
FYI I think release was something we did because @thibautjombart wanted a version to use in the field in an Ebola outbreak (last year or the one before). 
Are we happy with this and can we close this issue? @jstockwin and @zkamvar ?

**Comment by jstockwin** [comment]
Yep, this can definitely be closed!

**Comment by zkamvar** [comment]
Agreed.

I believe the original idea behind the release branch was @richfitz. This was so that you could point the deployer to that branch and easily point people to the last known working version. The only problem was that it required you to actually push to the release branch every time you made a release.

**Comment by jstockwin** [comment]
Now that we have proper [releases](https://github.com/annecori/EpiEstim/releases) this isn't a problem, though? You can just target `EpiEstim@v2.1-0`.

**Comment by zkamvar** [comment]
No, it isn't really a problem at all... It's just that someone needs to be on top of it in the future.
