### ISSUE TITLE
Ugly TableGrob output in knitr documents when plot() called

### ISSUE THREAD

**Issue by timchurches** [annecori/EpiEstim#86]
Calling the plot() function in a code block in a knitr document results in ugly and distracting TableGrob information being included in the final knitted document (documents such as https://cbdrh.github.io/NovelCoronavirus/on-COVID-19.html ). Using warning=FALSE and message=FALSE options for the code chunk does not suppress the TableGrob messages. The underlying issue is discussed here: https://stackoverflow.com/questions/39268103/cannot-disable-r-markdown-output-from-gridextra-additional-comment

A work-around is to define a custom aggregate plot and use that directly, as below.  

```
# custom results plotting function to avoid the ugly
# TableGrob messages returned by the plotting function
# in the EpiEstim package
plot_Ri <- function(estimate_R_obj) {
  p_I <- plot(estimate_R_obj, "incid", add_imported_cases=TRUE) # plots the incidence
  p_SI <- plot(estimate_R_obj, "SI") # plots the serial interval distribution
  p_Ri <- plot(estimate_R_obj, "R")
  return(gridExtra::grid.arrange(p_I, p_SI, p_Ri, ncol = 1))
}

hubei_res_parametric_si <- estimate_R(hubei_confirmed_cases,
                                      method="parametric_si",
                                      config = make_config(list(
                                                           mean_si = 7.5, 
                                                           std_si = 3.4)))

plot_Ri(hubei_res_parametric_si)
```

**Comment by annecori** [comment]
Dear @timchurches 
thanks for the message and the suggested fix; I am on maternity leave and have limited time to deal with this, so as it is not a bug and you seem to have found a workaround I may leave it for now...
If you are able to put in a PR with your fix, @robin-thompson or @jstockwin may be able to review and incorporate your changes. 
Anyway, very glad to see this used for analyses of COVID-19 transmissibility!
Best
Anne

**Comment by timchurches** [comment]
Thanks @annecori, I see that @zkamvar has already submitted a PR for it. Many thanks!  We're trying to get our health data science post-grad students up to speed with all the RECON packages in anticipation of what is likely to happen, especially in our immediate Asia-Pacific region. Great work on the whole RECON thing. We'll try to submit PRs for minor improvements as we go.

Regards,

Tim C

**Comment by jstockwin** [comment]
Hey @timchurches, thanks for filing the issue.

Feel free to request a review from myself if you submit any PRs - I'll try to get round to reviewing anything as soon as I can!
