### ISSUE TITLE
x-y error in incidence plot

### ISSUE THREAD

**Issue by rdlarah** [annecori/EpiEstim#95]
Hi there,

thanks for the excellent package. It seems however that I'm not able to reproduce the plots I've seen elsewhere (for example on https://shiny.epidemiology.net/epiestim/)

Here's an example (using the current CRAN version, EpiEstim_2.2-1):

library(EpiEstim)
data(Flu1918)
R_i <- estimate_R(Flu1918$incidence, 
             method = "non_parametric_si", 
             config = list(t_start = seq(2, 26), t_end = seq(8, 32), 
             si_distr = Flu1918$si_distr))

plot(R_i, what = "incid")

Here's what I get:

![incid_plot](https://user-images.githubusercontent.com/64475701/80488453-a6683600-895e-11ea-92bc-07dd9351f370.png)

I think the labels are correct but the x and y values are swapped.

What am I missing?

Thanks in advance.
Harald

**Comment by thibautjombart** [comment]
Hi there, 
this is a bug in the new version of *ggplot2* which has been fixed in the recent release of *incidence*; can you update the package and try again?

**Comment by rdlarah** [comment]
Thank you, Thibaut!

Updating the incidence package fixed the issue.

Stay healthy!

Cheers
Harald

**Comment by thibautjombart** [comment]
No worries - you too!
